const express = require('express');
const fs = require('fs');
const path = require('path');

const pool = require('../db');
const { authenticateToken } = require('../middleware/auth');
const { requirePermission } = require('../middleware/rbac');
const ReportService = require('../services/reportService');
const {
  hasFieldErrors,
  isBlank,
  normalizeBoolean,
  normalizeEnumValue,
  respondValidationError,
  sanitizePayloadObject,
  sanitizeText,
  validateDateRange,
} = require('../utils/adminValidation');

const router = express.Router();
const reportService = new ReportService();

const DOWNLOAD_STREAM_HIGH_WATER_MARK = 64 * 1024;
const LONG_RUNNING_REPORT_TIMEOUT_MS = 5 * 60 * 1000;

const getValidReportTypes = () => reportService.getReportTypes();
const getValidReportFormats = () => reportService.getReportFormats();

const safeInteger = (value, fallback = 0) => {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const errorToStatusCode = (error) => {
  if (error && Number.isInteger(error.statusCode)) {
    return error.statusCode;
  }
  if (error && Number.isInteger(error.status)) {
    return error.status;
  }
  return 500;
};

const normalizeStringFilter = (value, maxLength = 120) => sanitizeText(value, { maxLength });

const extendLongRunningTimeout = (req, res, timeoutMs = LONG_RUNNING_REPORT_TIMEOUT_MS) => {
  if (req && typeof req.setTimeout === 'function') {
    req.setTimeout(timeoutMs);
  }

  if (res && typeof res.setTimeout === 'function') {
    res.setTimeout(timeoutMs);
  }
};

const hasResponseBeenCommitted = (res) => Boolean(res?.headersSent || res?.writableEnded);

const normalizeReportFilters = (payload = {}) => {
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
    return {};
  }

  const source = sanitizePayloadObject(payload);
  return {
    vaccineType: normalizeStringFilter(source.vaccineType, 100),
    status: normalizeStringFilter(source.status, 40).toLowerCase(),
    barangay: normalizeStringFilter(source.barangay, 120),
    ageGroup: normalizeStringFilter(source.ageGroup, 50),
    itemType: normalizeStringFilter(source.itemType, 80),
    lowStockOnly: normalizeBoolean(source.lowStockOnly, false),
    category: normalizeStringFilter(source.category, 100),
    type: normalizeStringFilter(source.type, 100),
    healthCenter: normalizeStringFilter(source.healthCenter, 120),
    vaccinationStatus: normalizeStringFilter(source.vaccinationStatus, 40),
    targetGroup: normalizeStringFilter(source.targetGroup, 50),
    includeVaccination: normalizeBoolean(source.includeVaccination, true),
    includeInventory: normalizeBoolean(source.includeInventory, true),
    includeAppointments: normalizeBoolean(source.includeAppointments, true),
    includeGuardians: normalizeBoolean(source.includeGuardians, true),
    includeInfants: normalizeBoolean(source.includeInfants, true),
  };
};

const normalizeDateFilters = ({ startDate, endDate }) => {
  const normalizedStartDate = sanitizeText(startDate, { maxLength: 32 });
  const normalizedEndDate = sanitizeText(endDate, { maxLength: 32 });

  const dateErrors = validateDateRange({
    startDate: normalizedStartDate,
    endDate: normalizedEndDate,
    startKey: 'startDate',
    endKey: 'endDate',
    startLabel: 'Start date',
    endLabel: 'End date',
  });

  return {
    normalizedStartDate,
    normalizedEndDate,
    dateErrors,
  };
};

const mapServiceErrorMessage = (statusCode, error, fallbackMessage) => {
  if (statusCode >= 500) {
    return fallbackMessage;
  }

  if (error && error.message) {
    return error.message;
  }

  return fallbackMessage;
};

// All report routes require authenticated SYSTEM_ADMIN access.
router.use(authenticateToken);

// GET /api/reports - Report history
router.get('/', requirePermission('report:view'), async (req, res) => {
  try {
    const VALID_REPORT_TYPES = getValidReportTypes();
    const { type, startDate, endDate, limit = 50, offset = 0, generatedBy } = req.query;

    const normalizedType = normalizeEnumValue(type, VALID_REPORT_TYPES, '');
    const normalizedGeneratedBy = safeInteger(generatedBy, 0);
    const normalizedLimit = Math.min(Math.max(safeInteger(limit, 50), 1), 200);
    const normalizedOffset = Math.max(safeInteger(offset, 0), 0);

    const { normalizedStartDate, normalizedEndDate, dateErrors } = normalizeDateFilters({
      startDate,
      endDate,
    });

    const validationErrors = {
      ...dateErrors,
    };

    if (!isBlank(type) && !normalizedType) {
      validationErrors.type = `Report type must be one of: ${VALID_REPORT_TYPES.join(', ')}`;
    }

    if (!isBlank(generatedBy) && normalizedGeneratedBy <= 0) {
      validationErrors.generatedBy = 'Generated by must be a valid user ID.';
    }

    if (hasFieldErrors(validationErrors)) {
      return respondValidationError(res, validationErrors);
    }

    const historyFilters = {
      limit: normalizedLimit,
      offset: normalizedOffset,
    };

    if (!isBlank(normalizedType)) {
      historyFilters.type = normalizedType;
    }

    if (!isBlank(normalizedStartDate)) {
      historyFilters.startDate = normalizedStartDate;
    }

    if (!isBlank(normalizedEndDate)) {
      historyFilters.endDate = normalizedEndDate;
    }

    if (normalizedGeneratedBy > 0) {
      historyFilters.generatedBy = normalizedGeneratedBy;
    }

    const reports = await reportService.getReportHistory(historyFilters);

    return res.json({
      success: true,
      data: reports,
      pagination: {
        limit: normalizedLimit,
        offset: normalizedOffset,
        total: reports.length,
      },
    });
  } catch (error) {
    console.error('Error fetching reports history:', error);
    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to fetch reports history.'),
      error: error.code || undefined,
    });
  }
});

// GET /api/reports/templates - Available report templates
router.get('/templates', requirePermission('report:view'), async (_req, res) => {
  try {
    const templates = reportService.getReportTemplates();
    return res.json({
      success: true,
      data: templates,
    });
  } catch (error) {
    console.error('Error fetching report templates:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch report templates.',
    });
  }
});

// GET /api/reports/admin/summary - Admin dashboard summary for reports module
router.get('/admin/summary', requirePermission('report:view'), async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    const requestedScope = String(req.query.scope || '').trim().toLowerCase();
    const scopeIds = [...new Set(
      [req.user?.clinic_id, req.user?.facility_id]
        .map((value) => Number.parseInt(value, 10))
        .filter((value) => Number.isInteger(value) && value > 0),
    )];
    const { normalizedStartDate, normalizedEndDate, dateErrors } = normalizeDateFilters({
      startDate,
      endDate,
    });

    if (hasFieldErrors(dateErrors)) {
      return respondValidationError(res, dateErrors);
    }

    const summary = await reportService.getAdminSummary({
      startDate: normalizedStartDate || undefined,
      endDate: normalizedEndDate || undefined,
      facilityId:
        requestedScope === 'system' || scopeIds.length === 0
          ? null
          : scopeIds[0],
      scopeIds: requestedScope === 'system' ? [] : scopeIds,
    });

    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
    res.setHeader('Pragma', 'no-cache');

    return res.json({
      success: true,
      data: summary,
    });
  } catch (error) {
    console.error('Error fetching report admin summary:', error);
    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to fetch report summary.'),
      error: error.code || undefined,
    });
  }
});

// GET /api/reports/stats - Report generation statistics grouped by type
router.get('/stats', requirePermission('report:view'), async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    const { normalizedStartDate, normalizedEndDate, dateErrors } = normalizeDateFilters({
      startDate,
      endDate,
    });

    if (hasFieldErrors(dateErrors)) {
      return respondValidationError(res, dateErrors);
    }

    const hasFileSizeColumnResult = await pool.query(
      `
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'reports'
          AND column_name = 'file_size'
        LIMIT 1
      `,
    );
    const hasFileSizeColumn = hasFileSizeColumnResult.rows.length > 0;

    let statsQuery = `
      SELECT
        type,
        COUNT(*)::int AS count,
        ROUND((COUNT(*) * 100.0) / NULLIF(SUM(COUNT(*)) OVER(), 0), 2) AS percentage,
        ${hasFileSizeColumn ? 'COALESCE(SUM(file_size), 0)::bigint' : '0::bigint'} AS total_size,
        ROUND(AVG(EXTRACT(EPOCH FROM (NOW() - date_generated)) / 86400), 2) AS avg_age_days
      FROM reports
      WHERE 1=1
    `;

    const statsParams = [];
    let paramIndex = 1;

    if (!isBlank(normalizedStartDate)) {
      statsQuery += ` AND date_generated::date >= $${paramIndex}`;
      statsParams.push(normalizedStartDate);
      paramIndex += 1;
    }

    if (!isBlank(normalizedEndDate)) {
      statsQuery += ` AND date_generated::date <= $${paramIndex}`;
      statsParams.push(normalizedEndDate);
      paramIndex += 1;
    }

    statsQuery += ' GROUP BY type ORDER BY count DESC';

    const statsResult = await pool.query(statsQuery, statsParams);
    return res.json({
      success: true,
      data: statsResult.rows,
    });
  } catch (error) {
    console.error('Error fetching report stats:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch report stats.',
    });
  }
});

// POST /api/reports/generate - Generate a report file and persist metadata
router.post('/generate', requirePermission('report:create'), async (req, res) => {
  try {
    extendLongRunningTimeout(req, res);

    const VALID_REPORT_TYPES = getValidReportTypes();
    const VALID_REPORT_FORMATS = getValidReportFormats();
    const { id: userId } = req.user;
    const { type, format = 'pdf', startDate, endDate, filters = {} } = req.body || {};

    const normalizedType = normalizeEnumValue(type, VALID_REPORT_TYPES, '');

    const normalizedFormatInput = sanitizeText(format).toLowerCase();
    const normalizedFormat = normalizedFormatInput === 'xlsx' ? 'excel' : normalizedFormatInput;
    const normalizedSafeFormat = normalizeEnumValue(
      normalizedFormat,
      VALID_REPORT_FORMATS,
      '',
    );

    const { normalizedStartDate, normalizedEndDate, dateErrors } = normalizeDateFilters({
      startDate,
      endDate,
    });

    const validationErrors = {
      ...dateErrors,
    };

    if (isBlank(type)) {
      validationErrors.type = 'Report type is required.';
    } else if (!normalizedType) {
      validationErrors.type = `Report type must be one of: ${VALID_REPORT_TYPES.join(', ')}`;
    }

    if (isBlank(format)) {
      validationErrors.format = 'Report format is required.';
    } else if (!normalizedSafeFormat) {
      validationErrors.format = `Report format must be one of: ${VALID_REPORT_FORMATS.join(', ')}`;
    }

    if (hasFieldErrors(validationErrors)) {
      return respondValidationError(res, validationErrors);
    }

    const normalizedFilters = normalizeReportFilters(filters);
    const generationFilters = {
      ...normalizedFilters,
      startDate: normalizedStartDate || undefined,
      endDate: normalizedEndDate || undefined,
    };

    const report = await reportService.generateReport(
      normalizedType,
      generationFilters,
      normalizedSafeFormat,
      userId,
    );

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    return res.status(201).json({
      success: true,
      message: 'Report generated successfully.',
      data: report,
    });
  } catch (error) {
    console.error('Error generating report:', error);

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to generate report.'),
      error: error.code || undefined,
    });
  }
});

// POST /api/reports/batch-generate - Generate multiple reports in sequence
router.post('/batch-generate', requirePermission('report:create'), async (req, res) => {
  try {
    extendLongRunningTimeout(req, res);

    const VALID_REPORT_TYPES = getValidReportTypes();
    const VALID_REPORT_FORMATS = getValidReportFormats();
    const { id: userId } = req.user;
    const { reports } = req.body || {};

    if (!Array.isArray(reports) || reports.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Reports array is required.',
      });
    }

    const results = [];
    let successCount = 0;
    let failureCount = 0;

    for (const reportConfig of reports) {
      try {
        const reportType = normalizeEnumValue(reportConfig?.type, VALID_REPORT_TYPES, '');
        const rawFormat = sanitizeText(reportConfig?.format || 'pdf').toLowerCase();
        const reportFormat = normalizeEnumValue(
          rawFormat === 'xlsx' ? 'excel' : rawFormat,
          VALID_REPORT_FORMATS,
          '',
        );

        if (!reportType) {
          throw reportService.createHttpError(
            `Invalid report type: ${reportConfig?.type || '(empty)'}`,
            400,
            'REPORT_INVALID_TYPE',
          );
        }

        if (!reportFormat) {
          throw reportService.createHttpError(
            `Invalid report format: ${reportConfig?.format || '(empty)'}`,
            400,
            'REPORT_INVALID_FORMAT',
          );
        }

        const reportFilters = normalizeReportFilters(reportConfig?.filters || {});
        const reportPayload = {
          ...reportFilters,
          startDate: sanitizeText(reportConfig?.startDate, { maxLength: 32 }) || undefined,
          endDate: sanitizeText(reportConfig?.endDate, { maxLength: 32 }) || undefined,
        };

        const generatedReport = await reportService.generateReport(
          reportType,
          reportPayload,
          reportFormat,
          userId,
        );

        results.push({
          config: reportConfig,
          success: true,
          report: generatedReport,
        });
        successCount += 1;
      } catch (itemError) {
        results.push({
          config: reportConfig,
          success: false,
          error: itemError.message,
          code: itemError.code || 'REPORT_BATCH_ITEM_FAILED',
        });
        failureCount += 1;
      }
    }

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    return res.status(201).json({
      success: true,
      message: `Batch generation completed: ${successCount} successful, ${failureCount} failed.`,
      results,
    });
  } catch (error) {
    console.error('Error during batch report generation:', error);

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to run batch report generation.'),
      error: error.code || undefined,
    });
  }
});

// GET /api/reports/:id/status - Check report status metadata
router.get('/:id/status', requirePermission('report:view'), async (req, res) => {
  try {
    const reportId = safeInteger(req.params.id, 0);
    if (reportId <= 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid report ID.',
      });
    }

    const statusData = await reportService.getReportStatus(reportId);
    return res.json({
      success: true,
      data: statusData,
    });
  } catch (error) {
    console.error('Error fetching report status:', error);
    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to fetch report status.'),
      error: error.code || undefined,
    });
  }
});

// GET /api/reports/:id - Fetch report metadata row
router.get('/:id', requirePermission('report:view'), async (req, res) => {
  try {
    const reportId = safeInteger(req.params.id, 0);
    if (reportId <= 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid report ID.',
      });
    }

    const reportResult = await pool.query('SELECT * FROM reports WHERE id = $1 LIMIT 1', [reportId]);
    if (reportResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'Report not found.',
      });
    }

    return res.json({
      success: true,
      data: reportResult.rows[0],
    });
  } catch (error) {
    console.error('Error fetching report details:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch report details.',
    });
  }
});

// GET /api/reports/:id/download - Download report file by metadata ID
router.get('/:id/download', requirePermission('report:export'), async (req, res) => {
  try {
    extendLongRunningTimeout(req, res);

    const reportId = safeInteger(req.params.id, 0);
    if (reportId <= 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid report ID.',
      });
    }

    const downloadResult = await reportService.downloadReport(reportId);

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    await pool.query('UPDATE reports SET download_count = download_count + 1 WHERE id = $1', [reportId]);

    res.setHeader('Content-Type', downloadResult.mimeType);
    res.setHeader('Content-Disposition', `attachment; filename="${downloadResult.filename}"`);
    res.setHeader('Content-Length', String(downloadResult.fileSize));
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
    res.setHeader('Pragma', 'no-cache');

    const fileStream = fs.createReadStream(downloadResult.path, {
      highWaterMark: DOWNLOAD_STREAM_HIGH_WATER_MARK,
    });

    fileStream.on('error', (streamError) => {
      console.error('Report stream read error:', streamError);
      if (!res.headersSent) {
        res.status(500).json({
          success: false,
          message: 'Failed to stream report file.',
        });
      } else {
        res.destroy(streamError);
      }
    });

    res.on('close', () => {
      if (!fileStream.closed) {
        fileStream.destroy();
      }
    });

    return fileStream.pipe(res);
  } catch (error) {
    console.error('Error downloading report:', error);

    if (hasResponseBeenCommitted(res)) {
      return;
    }

    const statusCode = errorToStatusCode(error);
    return res.status(statusCode).json({
      success: false,
      message: mapServiceErrorMessage(statusCode, error, 'Failed to download report.'),
      error: error.code || undefined,
    });
  }
});

// DELETE /api/reports/:id - Delete report metadata and stored file
router.delete('/:id', requirePermission('report:export'), async (req, res) => {
  try {
    const reportId = safeInteger(req.params.id, 0);
    if (reportId <= 0) {
      return res.status(400).json({
        success: false,
        message: 'Invalid report ID.',
      });
    }

    const reportResult = await pool.query(
      'SELECT id, file_path FROM reports WHERE id = $1 LIMIT 1',
      [reportId],
    );

    if (reportResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'Report not found.',
      });
    }

    const reportRow = reportResult.rows[0];
    const filePath = sanitizeText(reportRow.file_path, { maxLength: 500 });

    if (!isBlank(filePath)) {
      const resolvedPath = path.isAbsolute(filePath)
        ? filePath
        : path.join(__dirname, '..', 'uploads', 'reports', filePath);

      fs.promises.unlink(resolvedPath).catch((unlinkError) => {
        console.warn(`Report file delete skipped for ${resolvedPath}:`, unlinkError.message);
      });
    }

    await pool.query('DELETE FROM reports WHERE id = $1', [reportId]);

    return res.json({
      success: true,
      message: 'Report deleted successfully.',
    });
  } catch (error) {
    console.error('Error deleting report:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to delete report.',
    });
  }
});

module.exports = router;
