const pool = require('../db');

const INFANT_CONTROL_NUMBER_PATTERN = /^INF-\d{4}-\d{6}$/;

const normalizeName = (value = '') =>
  String(value || '')
    .trim()
    .replace(/\s+/g, ' ')
    .toLowerCase();

const normalizeSex = (value = 'other') => {
  const normalized = String(value || '')
    .trim()
    .toLowerCase();

  if (normalized === 'm' || normalized === 'male') {
    return 'male';
  }

  if (normalized === 'f' || normalized === 'female') {
    return 'female';
  }

  return 'other';
};

const toIsoDate = (value) => {
  if (!value) {
    return null;
  }

  const parsed = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return null;
  }

  return parsed.toISOString().split('T')[0];
};

const sanitizeControlNumber = (value) => String(value || '').trim().toUpperCase();

const generateControlNumber = async (client = pool) => {
  const fallbackYear = new Date().getFullYear();

  try {
    const result = await client.query('SELECT fn_generate_infant_control_number() AS control_number');
    const generated = sanitizeControlNumber(result.rows?.[0]?.control_number);

    if (INFANT_CONTROL_NUMBER_PATTERN.test(generated)) {
      return generated;
    }

    throw new Error('Invalid control number generated by fn_generate_infant_control_number()');
  } catch (_error) {
    try {
      const result = await client.query('SELECT nextval(\'infant_control_number_seq\') AS seq');
      const seq = parseInt(result.rows?.[0]?.seq, 10);

      if (!Number.isFinite(seq)) {
        throw new Error('Invalid sequence value for infant_control_number_seq');
      }

      return `INF-${fallbackYear}-${String(seq).padStart(6, '0')}`;
    } catch (_legacyError) {
      const fallbackSuffix = String(Date.now()).slice(-6);
      return `INF-${fallbackYear}-${fallbackSuffix}`;
    }
  }
};

const getPatientControlNumberById = async (patientId, client = pool) => {
  const result = await client.query(
    `
      SELECT control_number
      FROM patients
      WHERE id = $1
      LIMIT 1
    `,
    [patientId],
  );

  return sanitizeControlNumber(result.rows?.[0]?.control_number || null) || null;
};

const ensurePatientControlNumber = async (patientId, client = pool) => {
  const existingControlNumber = await getPatientControlNumberById(patientId, client);
  if (existingControlNumber) {
    return existingControlNumber;
  }

  const generatedControlNumber = await generateControlNumber(client);

  await client.query(
    `
      UPDATE patients
      SET control_number = $1,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = $2
    `,
    [generatedControlNumber, patientId],
  );

  return generatedControlNumber;
};

const findMatchingActivePatients = async (
  { guardianId, firstName, lastName, dob },
  client = pool,
) => {
  if (!guardianId || !firstName || !lastName || !dob) {
    return [];
  }

  const result = await client.query(
    `
      SELECT id, control_number, created_at
      FROM patients
      WHERE guardian_id = $1
        AND is_active = true
        AND LOWER(REGEXP_REPLACE(TRIM(first_name), '\\s+', ' ', 'g')) = $2
        AND LOWER(REGEXP_REPLACE(TRIM(last_name), '\\s+', ' ', 'g')) = $3
        AND dob = $4::date
      ORDER BY created_at ASC NULLS LAST, id ASC
      FOR UPDATE
    `,
    [
      guardianId,
      normalizeName(firstName),
      normalizeName(lastName),
      toIsoDate(dob),
    ],
  );

  return result.rows || [];
};

const buildInsertPayload = ({
  guardianId,
  firstName,
  lastName,
  dob,
  sex,
  controlNumber,
  initialValues = {},
}) => {
  const fullName = `${firstName || ''} ${lastName || ''}`.trim();
  const payload = {
    name: fullName,
    first_name: String(firstName || '').trim(),
    last_name: String(lastName || '').trim(),
    dob: toIsoDate(dob),
    sex: normalizeSex(sex),
    guardian_id: guardianId || null,
    control_number: sanitizeControlNumber(controlNumber),
    is_active: true,
  };

  const optionalKeys = [
    'middle_name',
    'national_id',
    'address',
    'contact',
    'photo_url',
    'mother_name',
    'father_name',
    'birth_weight',
    'birth_height',
    'place_of_birth',
    'barangay',
    'health_center',
    'family_no',
    'time_of_delivery',
    'type_of_delivery',
    'doctor_midwife_nurse',
    'nbs_done',
    'nbs_date',
    'cellphone_number',
    'facility_id',
  ];

  optionalKeys.forEach((key) => {
    if (Object.prototype.hasOwnProperty.call(initialValues, key)) {
      payload[key] = initialValues[key];
    }
  });

  return payload;
};

const resolveOrCreateInfantPatient = async (
  {
    guardianId,
    firstName,
    lastName,
    dob,
    sex = 'other',
    initialValues = {},
  },
  client = pool,
) => {
  const normalizedFirstName = String(firstName || '').trim();
  const normalizedLastName = String(lastName || '').trim();
  const normalizedDob = toIsoDate(dob);

  if (!normalizedFirstName || !normalizedLastName || !normalizedDob) {
    throw new Error('firstName, lastName, and dob are required for infant identity resolution');
  }

  const parsedGuardianId = guardianId ? parseInt(guardianId, 10) : null;
  const hasGuardianScope = Number.isInteger(parsedGuardianId) && parsedGuardianId > 0;

  if (hasGuardianScope) {
    const matches = await findMatchingActivePatients(
      {
        guardianId: parsedGuardianId,
        firstName: normalizedFirstName,
        lastName: normalizedLastName,
        dob: normalizedDob,
      },
      client,
    );

    if (matches.length > 1) {
      const conflictError = new Error(
        'Multiple active patient records match this infant identity. Resolve duplicates before proceeding.',
      );
      conflictError.code = 'AMBIGUOUS_INFANT_MATCH';
      conflictError.matches = matches.map((row) => row.id);
      throw conflictError;
    }

    if (matches.length === 1) {
      const matchedPatient = matches[0];
      const controlNumber = await ensurePatientControlNumber(matchedPatient.id, client);

      return {
        id: matchedPatient.id,
        control_number: controlNumber,
        existed: true,
      };
    }
  }

  const generatedControlNumber = await generateControlNumber(client);
  const insertPayload = buildInsertPayload({
    guardianId: hasGuardianScope ? parsedGuardianId : null,
    firstName: normalizedFirstName,
    lastName: normalizedLastName,
    dob: normalizedDob,
    sex,
    controlNumber: generatedControlNumber,
    initialValues,
  });

  const columns = Object.keys(insertPayload);
  const values = columns.map((columnName) => insertPayload[columnName]);
  const placeholders = columns.map((_, index) => `$${index + 1}`);

  const insertResult = await client.query(
    `
      INSERT INTO patients (${columns.join(', ')})
      VALUES (${placeholders.join(', ')})
      RETURNING id, control_number
    `,
    values,
  );

  return {
    id: insertResult.rows[0].id,
    control_number: sanitizeControlNumber(insertResult.rows[0].control_number),
    existed: false,
  };
};

module.exports = {
  INFANT_CONTROL_NUMBER_PATTERN,
  normalizeName,
  normalizeSex,
  toIsoDate,
  generateControlNumber,
  getPatientControlNumberById,
  ensurePatientControlNumber,
  resolveOrCreateInfantPatient,
  buildInsertPayload,
};
